# test message bus telemetry

test: FORCE
	./test_reprocessor


# remove intermediate test result files

clean: FORCE
	rm -f ../../../../tomcat-text/reprocessor_test_input
	rm -f ../../../../tomcat-text/reprocessor_test_output
	rm -f output/*.*

FORCE: ;
