# test the Reprocessor Dialog Agent
.PHONY: test
test:
	./test_reprocessor_agent

# remove test result files
.PHONY: clean
clean:
	rm -f ../../../../tomcat-text/reprocessor_test_input
	rm -f ../../../../tomcat-text/reprocessor_test_output
	rm -f output/*.*
