# test the Reprocessor Dialog Agent
.PHONY: test
test:
	./test_reprocessor_agent

# remove test result files
.PHONY: clean
clean:
	rm -f test_results/test_results.metadata
	rm -f test_results/test_results.json
