#!/bin/bash

# Author: Joseph Astier

# Reprocessor testing

# Reprocess DialogAgent metadata and compare the output with
# an expected file

echo ""
echo ""
echo "REPROCESSOR AGENT TESTING: "

# paths to this directory
this_dir=$(pwd)
input_dir="$this_dir/input"
test_results_dir="$this_dir/test_results"
expected_results_dir="$this_dir/expected_results"

echo "Input files:"
echo $(ls $input_dir)

# expected result in pretty-format JSON
expected_results_json="$expected_results_dir/expected.json"
test_results_metadata="$test_results_dir/reprocessor_test.metadata"
test_results_json="$test_results_dir/test_results.json"

# Remove previous test results
rm -f $test_results_metadata
rm -f $test_results_json

# Move to tomcat-text repo directory
cd ../../../../tomcat-text

# Run the reprocessor on the linked directories
echo "Starting Reprocesor Agent:"
sbt "runMain org.clulab.asist.apps.RunDialogAgent reprocess \
    $input_dir $test_results_dir"

cd $this_dir

# translate compact JSON metadata into pretty JSON for diffing by line
jq < $test_results_metadata > $test_results_json

# Only the timestamps should differ
echo "Test input: $input_metadata"
echo "expected results: $expected_results_json"
echo "test results: $test_results_json"
echo "Diffing expected results and test results:"
diff $expected_results_json $test_results_json

exit 0

