#!/bin/bash

# Author: Joseph Astier

echo "MQTT AGENT TESTING: full trial"

this_dir=$(pwd)

# simulate a full Message Bus trial
function test_full_trial () {
    cd trial_start; ./test_trial_start; cd $this_dir
    cd rollcall_request; ./test_rollcall_request; cd $this_dir
    cd chat; ./test_chat; cd $this_dir
    cd asr; ./test_asr; cd $this_dir
    cd rollcall_request; ./test_rollcall_request; cd $this_dir
    cd chat; ./test_chat; cd $this_dir
    cd asr; ./test_asr; cd $this_dir
    cd rollcall_request; ./test_rollcall_request; cd $this_dir
    cd trial_stop; ./test_trial_stop; cd $this_dir
}

# simulate n Testbed trials
test_full_trial
test_full_trial
test_full_trial
