#!/bin/bash

# Author: Joseph Astier

echo "MQTT AGENT TESTING: n trials"

this_dir=$(pwd)

# simulate a full Message Bus trial
function test_full_trial () {
    cd trial_start; ./test_trial_start; cd $this_dir
    cd rollcall_request; ./test_rollcall_request; cd $this_dir
    cd chat; ./test_chat; cd $this_dir
    cd asr; ./test_asr; cd $this_dir
    cd rollcall_request; ./test_rollcall_request; cd $this_dir
    cd chat; ./test_chat; cd $this_dir
    cd asr; ./test_asr; cd $this_dir
    cd rollcall_request; ./test_rollcall_request; cd $this_dir
    cd trial_stop; ./test_trial_stop; cd $this_dir
}

# Start the MQTT agent
echo "Starting MQTT agent.   Testing will begin in 90 seconds"
cd ../../../../tomcat-text
sbt "runMain org.clulab.asist.apps.RunDialogAgent mqtt --host localhost --port 1883" &
mqtt_agent_pid="$!"

sleep 90 # weaksauce, we need to detect a running agent 

cd $this_dir
echo "testing ..."

# simulate n Testbed trials
test_full_trial
test_full_trial
test_full_trial

# stop the MQTT agent
kill $mqtt_agent_pid
echo "MQTT agent done"
