#!/bin/bash

# Author: Joseph Astier

# test name
test_name="dialog_agent_message_from_chat"

# published to the Message Bus to trigger production of result
publication_metadata="Testathon_3_24_2022_chat.metadata"

# subscription topic for result
subscription_topic="agent/dialog"

# expected result filename
expected_result_json="dialog_agent_message_from_chat_expected.json"

call="./mqtt_test $test_name $publication_metadata $subscription_topic $expected_result_json"

$call

exit 0
