#!/bin/bash

# Publish a text file to an MQTT topic one line at a time.

host="localhost"
port=1883
topic="agent/asr"
filename="asr_input.json"


printf "\nPublishing '$filename' on MQTT host '$host', port $port, topic '$topic'...\n\n"
while IFS= read -r line
do
  printf "$line\n"
  mosquitto_pub -h $host -p $port -t $topic -m "$line"
done < $filename
printf "\nDone publishing '$filename'\n"



