#!/bin/bash

# Author: Joseph Astier

# test name
test_name="version_info"

# published to the Message Bus to trigger production of result
publication_metadata="Testathon_3_24_2022_trial_start.metadata"

# subscription topic for result
subscription_topic="agent/tomcat_textAnalyzer/versioninfo"

# expected result filename
expected_result_json="version_info_expected.json"


call="./mqtt_test $test_name $publication_metadata $subscription_topic $expected_result_json"

$call

exit 0
