#!/usr/bin/env python

import json
from glob import glob
from tqdm import tqdm
from matplotlib import pyplot as plt

plt.style.use("ggplot")

# with open("all_extractions.txt", "w") as all_extractions:
    # for file in tqdm(glob("/Users/adarsh/scratch/2021_09_10/metadatafiles/*.metadata")):
        # with open(file) as f:
            # for line in f:
                # message = json.loads(line)
                # if "data" in message and "extractions" in message["data"]:
                    # all_extractions.write(json.dumps(message["data"]["extractions"])+"\n")

num_extractions = []
labels = {}
with open("all_extractions.txt") as f:
    for line in f:
        extractions = json.loads(line)
        num_extractions.append(len(extractions))
        for extraction in extractions:
            label = extraction["label"]
            if label not in labels:
                labels[label] = 1
            else:
                labels[label] += 1


# Make histograms
fig, ax = plt.subplots()
ax.hist(num_extractions)
plt.tight_layout()
fig.savefig("num_extractions_hist.pdf")

fig, ax = plt.subplots()
ax.bar(range(len(labels)), labels.values(), tick_label = labels.keys())
plt.tight_layout()
fig.savefig("num_extractions_labels.pdf")
