#!/usr/bin/env python3

import os
from subprocess import run
from pathlib import Path

# Get the path to the data directory, assuming that the repo directory
# structure is mirrored.


def sync_asist_data(dataset):
    choices = {
        1: "study-1_2020.08",
        2: "study-2_pilot-2_2021.02",
        3: "study-2_2021.06",
    }

    gcs_dir = choices[dataset]

    data_dir = (
        Path(os.path.dirname(os.path.realpath(__file__))).parent
        / "data/studies.aptima.com"
        / gcs_dir
    )

    os.makedirs(data_dir, exist_ok=True)

    extensions_to_exclude = {
        "sav",
        "pdf",
        "qsf",
        "mp4",
        "m4a",
        "wav",  # .wav files starting from study 2 onwards
        "txt",  # QC trial messages
        "metadata",  # from study 2 onwards
        "tsv",
        "png",
        "PNG",
        "xlsx",
        "zip",
        "csv",
        "fov",  # Extension for fov messages from study 1
        "docx",
    }

    if gcs_dir != "study-1_2020.08":
        extensions_to_exclude.remove("metadata")

    # Construct a regex for gsutil rsync exclusion
    exclusion_regex = (
        "$|".join((f".*\.{ext}" for ext in extensions_to_exclude)) + "$"
    )

    if gcs_dir == "study-2_2021.06":
        exclusion_regex = (
            exclusion_regex
            + "|.*FoV*"
            + "|.*Competency*"
            + "|.*Training*"
            + "|.*\.vtt$"
        )

    run(
        [
            "gsutil",
            "-m",
            "rsync",
            "-r",
            "-x",
            exclusion_regex,
            f"gs://studies.aptima.com/{gcs_dir}",
            data_dir,
        ],
        cwd=data_dir,
    )


if __name__ == "__main__":
    from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

    parser = ArgumentParser(
        description="sync_asist_data",
        formatter_class=ArgumentDefaultsHelpFormatter,
    )

    help_text = (
        "Dataset to sync. 1: Study 1, 2: Study 2 pilot, 3: Study 2 HSR data"
    )

    parser.add_argument("dataset", type=int, help=help_text, choices=(1, 2, 3))
    args = parser.parse_args()

    # Study 1 GCS dir: study-1_2020.08
    # Study 2 pilot GCS dir: study-2_pilot-2_2021.02
    # Study 2 HSR data GCS dir: study-2_2021.06

    sync_asist_data(args.dataset)
