# This is a basic workflow to help you get started with Actions

name: Deploy website to Github Pages

on:
  push:
    branches: 
      - master

jobs:
  deploy_docs:
    runs-on: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.232'

    - name: Build docs
      run: |
        sudo apt-get install -y pandoc
        make htmldoc
        mv extraction_schemas.html index.html

    - name: Deploy docs to clulab.github.io/tomcat-text
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: .
